spring:
  application:
    name: online-office-miniApp
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.100:3306/OnlineOfficeDB?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 8
      max-active: 16
      max-wait: 60000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
  redis:
    port: 6379
    host: 192.168.1.100
    database: 0
    jedis:
      pool:
        max-active: 500
        max-wait: -1ms
        max-idle: 8
        min-idle: 4
  data:
    mongodb:
      host: 192.168.1.100
      port: 27017
      database: OnlineOffice
      authentication-database: admin
      username: yang
      password: '1214'
  mail:
    host: smtp.163.com
    default-encoding: UTF-8
    username: yanghan1214@163.com
    password: 12141996yh


server:
  tomcat:
    max-threads: 200
    min-spare-threads: 30
    connection-timeout: 5000ms
  port: 8899

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    use-generated-keys: true #回写主键

yang:
  jwt:
    secret: abc123456   #密钥
    expire: 5           #令牌过期时间
    cache-expire: 10    #令牌缓存时间

  wx:
    app-id: wx2c1e7907990c1910
    app-secret: d390a06feca08618bc169fff821a79de

  face:
    createFaceModelUrl: http://192.168.1.222:3000/create_face_model
    checkinUrl: http://192.168.1.222:3000/checkin

  code: HelloWorld

  email:
    system: yanghan1214@163.com
    hr: yh695708271@qq.com

  image-folder: /Users/yanghan/Desktop/Project/project2/OnlineOfiice/src/main/resources/image
  face-model-folder: /Users/yanghan/Desktop/Project/project2/OnlineOfiice/src/main/resources/model

  recieveNotify: http://192.168.1.100:8899/meeting/recieveNotify  #接收会议审批结果

alibaba:  #阿里云信息
  cloud:
    oss:
      endpoint: https://oss-cn-beijing.aliyuncs.com
    secret-key: UEFRiCfuneqFZ1r5bLXI4ozAHbAR9U
    access-key: LTAI5tHPgLntqYRTb671AfiF



